name: CI

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check if Prisma is used
        id: prisma_check
        run: |
          if [ -f prisma/schema.prisma ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Prisma client
        if: steps.prisma_check.outputs.exists == 'true'
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Unit test
        run: npm run test
